---
#This is playbook will install Supervisor on redhat 

# Install python-setuptools
- name: Install python-setuptools
  yum: 
        pkg=python-setuptools
        state=present 

# Instaling easy_install package        
- name: Install supervisor
  shell: easy_install supervisor

# Creating a directory        
- name: Creating the file directory
  file: path="{{ supervisor.create.dir }}"
     state=directory 
     mode=0755        
     
#  Copy service files 
- name: copy services file 
  template: src="{{ supervisor.service.file }}"
            dest="{{ supervisor.service.path }}"

# Copy configure files
- name: copy configservice file to folder
  template: src="{{ supervisor.config.file }}"  dest="{{ supervisor.config.default }}"
  #template: src=visord.conf  dest=/etc/supervisord.d/supervisord.conf
 
 
# Restart the supervisror 
- name: Restart supervisord service
  service: name=supervisord state=restarted enabled=yes

